# Generated by Django 5.1.6 on 2025-02-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=7, unique=True, verbose_name='Foydalanuvchi ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqam')),
                ('full_name', models.CharField(max_length=100, verbose_name='Foydalanuvchi ismi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('total_points', models.FloatField(default=0, verbose_name='Jami ballar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol_type', models.IntegerField(choices=[(80, '80'), (91, '91'), (92, '92'), (95, '95')])),
                ('litres', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
    ]
