# Generated by Django 5.1.6 on 2025-02-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpurchase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='fuelpurchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Xarid sanasi'),
        ),
        migrations.AlterField(
            model_name='fuelpurchase',
            name='litres',
            field=models.FloatField(verbose_name='Yonilg‘i litri'),
        ),
        migrations.AlterField(
            model_name='fuelpurchase',
            name='petrol_type',
            field=models.IntegerField(choices=[(80, '80'), (91, '91'), (92, '92'), (95, '95')], verbose_name='Yonilg‘i turi'),
        ),
    ]
