# Generated by Django 5.1.6 on 2025-02-24 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_fuelpurchase_customer_alter_fuelpurchase_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moyka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol_type', models.IntegerField(choices=[(80, '80'), (91, '91'), (92, '92'), (95, '95')], verbose_name='Yonilg‘i turi')),
                ('summa', models.FloatField(verbose_name='Summasi')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Xarid sanasi')),
                ('service_type', models.CharField(choices=[('Ekonom', 'Ekonom'), ('Bussines', 'Bussines'), ('Premium', 'Premium')], max_length=10, verbose_name='Xizmat turi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer', verbose_name='Mijoz')),
            ],
        ),
    ]
