# Generated by Django 5.1.6 on 2025-02-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_moyka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyka',
            name='petrol_type',
        ),
    ]
