# Generated by Django 5.1.6 on 2025-02-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_moyka_petrol_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoykaCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=7, unique=True, verbose_name='Foydalanuvchi ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqam')),
                ('full_name', models.CharField(max_length=100, verbose_name='Foydalanuvchi ismi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('total_points', models.FloatField(default=0, verbose_name='Jami ballar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
