# Generated by Django 5.1.6 on 2025-02-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_moykacustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyka',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.moykacustomer', verbose_name='Mijoz'),
        ),
    ]
