# Generated by Django 5.1.6 on 2025-02-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_moyka_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyka',
            name='summa',
        ),
    ]
